import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "./components/navbar";
import Icon from "./components/icon";

import Link from "next/link";
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navbar>
        <div>
          <Link href="/">
            <Icon width={60} height={60}/>
          </Link>
        </div>
        <ul className="hidden md:flex gap-x-6 text-gray-200">
          <li>
            <Link href="/">
              <p className="link-underline">Home</p>
            </Link>
          </li>
          <li>
            <Link href="/resume">
              <p className="link-underline">Resume</p>
            </Link>
          </li>
        </ul>
      </Navbar>
      {children}
      </body>
    </html>
  );
}
